"""Data models for the trading bot."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import time


class Direction(Enum):
    LONG = "long"
    SHORT = "short"


class SetupType(Enum):
    ZIGZAG_BREAKOUT = "zigzag_breakout"       # Setup A
    ENDING_DIAGONAL = "ending_diagonal"       # Setup B
    TRIANGLE_BREAKOUT = "triangle_breakout"   # Setup C


class WaveType(Enum):
    IMPULSE = "impulse"
    ZIGZAG = "zigzag"
    FLAT = "flat"
    TRIANGLE = "triangle"
    DIAGONAL = "diagonal"


class Trend(Enum):
    UP = "up"
    DOWN = "down"
    SIDEWAYS = "sideways"


@dataclass
class SwingPoint:
    """A local high or low on the chart."""
    index: int         # bar index in the dataframe
    price: float
    timestamp: float
    is_high: bool      # True = swing high, False = swing low


@dataclass
class Wave:
    """A single wave segment between two swing points."""
    start: SwingPoint
    end: SwingPoint
    label: str = ""    # "1", "2", "3", "4", "5", "A", "B", "C", "D", "E"

    @property
    def length(self) -> float:
        return abs(self.end.price - self.start.price)

    @property
    def direction(self) -> Direction:
        return Direction.LONG if self.end.price > self.start.price else Direction.SHORT

    @property
    def pct_change(self) -> float:
        return (self.end.price - self.start.price) / self.start.price


@dataclass
class WaveStructure:
    """A complete wave structure (impulse, zigzag, triangle, etc.)."""
    wave_type: WaveType
    waves: list        # list of Wave objects
    confidence: float = 0.0  # 0.0 to 1.0

    @property
    def start_price(self) -> float:
        return self.waves[0].start.price

    @property
    def end_price(self) -> float:
        return self.waves[-1].end.price

    @property
    def trend(self) -> Trend:
        if self.end_price > self.start_price:
            return Trend.UP
        elif self.end_price < self.start_price:
            return Trend.DOWN
        return Trend.SIDEWAYS


@dataclass
class FibLevel:
    """A Fibonacci level with price and label."""
    ratio: float
    price: float
    label: str = ""


@dataclass
class Signal:
    """A trading signal generated by the strategy."""
    symbol: str
    timeframe: str
    setup_type: SetupType
    direction: Direction
    entry_price: float
    stop_loss: float
    targets: list          # list of FibLevel (take-profit targets)
    confidence: float      # 0.0 to 1.0
    factors: list = field(default_factory=list)  # list of strings describing factors
    timestamp: float = 0.0

    def __post_init__(self):
        if self.timestamp == 0.0:
            self.timestamp = time.time()

    @property
    def risk(self) -> float:
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward(self) -> float:
        if not self.targets:
            return 0.0
        return abs(self.targets[0].price - self.entry_price)

    @property
    def rr_ratio(self) -> float:
        if self.risk == 0:
            return 0.0
        return self.reward / self.risk

    @property
    def risk_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        return abs(self.entry_price - self.stop_loss) / self.entry_price


@dataclass
class WaveContext:
    """Context from a higher timeframe for hierarchical wave analysis.

    Captures where we are in the wave count on a higher TF so that
    lower-TF signals can be validated against the larger structure.
    """
    trend: Trend
    timeframe: str
    expected_direction: Optional[Direction] = None
    wave_label: str = ""       # e.g. "post_zigzag", "post_impulse"
    structure_type: str = ""   # e.g. "impulse", "zigzag", "triangle"
    confidence: float = 0.0


@dataclass
class Position:
    """An open trading position."""
    id: str
    symbol: str
    direction: Direction
    entry_price: float
    size: float            # in base currency
    margin: float          # in USDT
    leverage: int
    stop_loss: float
    take_profit: float
    signal: Signal
    open_time: float = 0.0
    close_time: float = 0.0
    close_price: float = 0.0
    pnl: float = 0.0
    is_open: bool = True

    def __post_init__(self):
        if self.open_time == 0.0:
            self.open_time = time.time()

    @property
    def unrealized_pnl(self) -> float:
        """Calculate unrealized PnL given a current price (use close_price as current)."""
        if not self.is_open:
            return self.pnl
        price = self.close_price if self.close_price > 0 else self.entry_price
        if self.direction == Direction.LONG:
            return (price - self.entry_price) * self.size
        else:
            return (self.entry_price - price) * self.size
